name: 🚀 Deploy PHP Site via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: appleboy/scp-action@master
        with:
          host: 217.21.84.50
          port: 65002
          username: u848820288
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/public_html/"
          overwrite: true
          exclude: |
            **/.git*
            node_modules/**
            .github/**
